### ISSUE TITLE
Tests: Build and run WebRTC unit tests

### ISSUE THREAD

**Issue by aisouard** [aisouard/libwebrtc#10]

**Comment by muellni** [comment]
I want to use `webrtc/api/test/fakeaudiocapturemodule.h` for my build of [node-webrtc](https://github.com/FAForever/node-webrtc). 
While `webrtc/api/BUILD.gn` seems to use the `rtc_include_tests` option for building the `webrtc/api/test/*` files, it looks like the `-DBUILD_TESTS=ON` cmake-option doesn't enable it anymore, is that correct?
Do you see any way to fix that?

**Comment by aisouard** [comment]
The `BUILD_TESTS` flag wasn't taken into account inside the `webrtc-src` CMake target.
I have no other choice than building all the test binaries, this will add 933 files to compile and I hope that it won't reopen #32.

Testing under branch `build-unit-tests`

**Comment by aisouard** [comment]
Travis takes too much time to compile the library with unit tests.
I'll retry tonight on my own machines then close the issue.

**Comment by aisouard** [comment]
Merged in branch `dev`.
