### ISSUE TITLE
Issues compiling on OSX.

### ISSUE THREAD

**Issue by n8o** [aisouard/libwebrtc#31]
OSX: 10.12.3
Xcode: 8.2.1

During compilation i get the following two errors.

debug_dump_writer.cc:108:3: error: [chromium-style] auto variable type must not deduce to a raw pointer type.
audio_network_adaptor_impl.cc:67:8: error: [chromium-style] auto variable type must not deduce to a raw pointer type

Has anyone seen this before and might be able to recommend a fix?

**Comment by aisouard** [comment]
I'm having this issue on Travis as well, it has been reported on the webrtc-discuss group: https://groups.google.com/forum/m/#!topic/discuss-webrtc/CeEQ4W4ABSI

I will open an issue tonight, or find a way to deal with this by disabling their clang plugin triggering that error for instance.

Le 9 mars 2017 19:07:05 GMT+01:00, Nate Burr <notifications@github.com> a écrit :
>OSX: 10.12.3
>Xcode: 8.2.1
>
>During compilation i get the following two errors.
>
>debug_dump_writer.cc:108:3: error: [chromium-style] auto variable type
>must not deduce to a raw pointer type.
>audio_network_adaptor_impl.cc:67:8: error: [chromium-style] auto
>variable type must not deduce to a raw pointer type
>
>Has anyone seen this before and might be able to recommend a fix?
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/aisouard/libwebrtc/issues/31

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by n8o** [comment]
I did a make clean and make. compiled everything just fine the second time. So maybe it isn't an actual issue?

**Comment by aisouard** [comment]
It looks like a bug occuring right from the WebRTC repository, since someone else is having the same issue.

I added the possibility to add extra arguments to the `gn gen` command, as a temporary fix, you can run CMake by setting `GN_EXTRA_ARGS` to `clang_use_chrome_plugins=false`, like this:

```
cmake -DGN_EXTRA_ARGS="clang_use_chrome_plugins=false" ..
```

I'm waiting for Travis to finish before closing the issue.

**Comment by aisouard** [comment]
Closing since Travis has built it successfully by setting `clang_use_chrome_plugins` to `false`.

Feel free to re-open the issue if the problem persists.
