### ISSUE TITLE
You might not want to pass -j to ninja

### ISSUE THREAD

**Issue by agouaillard** [aisouard/libwebrtc#34]
it is internally multithreaded and is doing a good job at finding the maximum number of thread.
Passing -j should then only be used to reduce the number of thread ninja would normally use, in case you are using the computer to do something else. Any number passed above the optimal number would result in decreased performance. The -j option is dangerous ...

**Comment by aisouard** [comment]
I felt that it was speeding up builds under Travis, it is in fact useless and dangerous to set it on a personal computer.
