### ISSUE TITLE
component has been deprecated

### ISSUE THREAD

**Issue by agouaillard** [aisouard/libwebrtc#37]
if you set component_build to true in a standalone libwebrtc build, it will yell at you.

There is no current supported way to compile a shared library.

**Comment by aisouard** [comment]
I also need to enforce static libraries inside pkg-config. Using shared libraries seemed pointless to me, since we would have to link about 100 of these.

**Comment by agouaillard** [comment]
then, you should not advertise usage of component_build in your readme .... :)

**Comment by aisouard** [comment]
Sure, as a hotfix!
I'll remove it completely tonight.
