### ISSUE TITLE
Is BUILD_DEB_PACKAGE working

### ISSUE THREAD

**Issue by 9a4gl** [aisouard/libwebrtc#42]
I tried with -DBUILD_DEB_PACKAGE=ON but it didn't created a deb package, am I doing something wrong ?

**Comment by aisouard** [comment]
That feature is not finished yet.
Did you try to execute the `make package` command or build the `PACKAGE.vcxproj` target ?

**Comment by 9a4gl** [comment]
make package works, need this so I can try arm version which I do cross compile. Put that make package is required in readme files, not everyone familiar with cmake.
