### ISSUE TITLE
Undefined reference when linking with libwebrtc

### ISSUE THREAD

**Issue by NadirRoGue** [aisouard/libwebrtc#74]
Hello everyone.

I have a problem trying to link libwebrtc with a project im working in. The project already comes with a cmake that looks for the library headers and the library itself (which it founds). 

I have compiled the library following the instructions in the README of this repository. However, when linking I get the following errors:

```
webrtc_stream_client.cpp:(.text+0x3896): undefined reference to `webrtc::CreateSessionDescription(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, webrtc::SdpParseError*)'
webrtc_stream_client.cpp:(.text+0x3da0): undefined reference to `webrtc::CreateIceCandidate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, webrtc::SdpParseError*)'
collect2: error: ld returned 1 exit status
```

I have read this
https://groups.google.com/forum/#!topic/discuss-webrtc/XFm9wYCg58c
about having similar issues, and resolved using the following args for cmake:

`-DGN_EXTRA_ARGS='use_custom_libcxx=false use_custom_libcxx_for_host=false'`

Without success. Any idea?

Im using Ubuntu 16.04 LTS, GCC 5.4

**Comment by agouaillard** [comment]
the https://devhub.vr.rwth-aachen.de/ptoharia/webstreamer repository does not explain where you should get the libwebrtc from. You should have asked them first.

Now, you can see in their cmake/FindWebrtc.cmake script that they are looking first for a pkg file, and then for a library file whose name would be "libwebrtc_full". No such library is generated by this current project, but it looks like vsimon's project does. You might want to give it a try.
https://github.com/vsimon/webrtcbuilds/

**Comment by NadirRoGue** [comment]
@agouaillard Thank you very much, Simon's tool worked flawlessly.
