### ISSUE TITLE
'include' directory missing after compiling

### ISSUE THREAD

**Issue by jmillan** [aisouard/libwebrtc#75]
## Build information:

- `platform`: MacOS Mojave 10.14
- `cmake options`: -DWEBRTC_BRANCH_HEAD=refs/branch-heads/70

## Issue:

`include` directory is missing from my `out` directory.

## Notes:

`lib` directory exists in my `out` directory and contains `libwebrtc.a`

**Comment by BeiKeJieDeLiuLangMao** [comment]
It's because webrtc's directory structure changed, you could reference this pr.
https://github.com/aisouard/libwebrtc/pull/62/commits/b41505260ed125461f18b45f3588798c08028145

**Comment by BeiKeJieDeLiuLangMao** [comment]
By the way, if you build M70, you need to copy /path/to/out/include/third_party/abseil-cpp/absl to  /path/to/out/include/.
Because some header files use absl/types/optional.h, witch belongs to /path/to/out/include/third_party/abseil-cpp/absl.

**Comment by jmillan** [comment]
Thanks @BeiKeJieDeLiuLangMao,

I'm a beginner with CMake yet, I'll give it a try. For now I've just copied the necessary files by hand.

**Comment by jmillan** [comment]
I can't even recall this issue. Let me close it.
